---

# Main tasks file for php-fpm role

- name: 'Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/{{ ansible_distribution_release | lower }}.yml"
  tags:
    - 'php-fpm::role'
    - 'php-fpm::config'
    - 'php-fpm::install'


- name: 'Include install tasks'
  include: "{{ role_path }}/tasks/install.yml"
  tags:
    - 'php-fpm::role'
    - 'php-fpm::install'


- name: 'Manage custom instances'
  include: "{{ role_path }}/tasks/manage_custom_instances.yml"
  when:
    - "{{ php_fpm_instance.name is defined }}"
    - "{{ php_fpm_instance.name != 'fpm' }}"
  tags:
    - 'php-fpm::role'
    - 'php-fpm::install'
    - 'php-fpm::config'


- name: 'Include configuration tasks'
  include: "{{ role_path }}/tasks/config.yml"
  tags:
    - 'php-fpm::role'
    - 'php-fpm::config'
